/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as decentralizerLotterySol from "./DecentralizerLottery.sol";
export type { decentralizerLotterySol };
import type * as iDecentralizedLotterySol from "./IDecentralizedLottery.sol";
export type { iDecentralizedLotterySol };
