version: '3.8'

services:
  backend:
    build: ./backend
    command: bash -c "
      ./wait-for-postgres.sh db && ./app"
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=Anacondaz1
    env_file:
      - .env
    volumes:
      - ./log:/build/log

  frontend:
    build: ./frontend_v2
    depends_on:
      - backend
    ports:
      - 5173:5173
    environment:
      - VITE_PORT=5173
    env_file:
      - .env

  db:
    restart: always
    image: postgres:16
    volumes:
      - ./schema/postgres:/docker-entrypoint-initdb.d
      # - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dbo
      - POSTGRES_PASSWORD=Anacondaz1
    ports:
      - 5432:5432