/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as decentralizerLotterySol from "./DecentralizerLottery.sol";
export * as iDecentralizedLotterySol from "./IDecentralizedLottery.sol";
